### ISSUE TITLE
It is impossible to bind listener to arbitrary because of the non-strict mode

### ISSUE THREAD

**Issue by anzome** [ai/nanoevents#22]
I've decided to write tests for the change done by https://github.com/ai/nanoevents/pull/21 and find that the pull request actually changed nothing.

In 'non-strict' mode `i.apply(null, args)` binds `this` to global object. I've missed this fact because of the habit to use ES modules everywhere. For them 'strict mode' enabled by default. This was the reason why I mistakenly extrapolated results of my small experiment on all cases.

```js
window.test = 'test'
function testFn() { console.log(this.test); }
testFn.bind(window).apply(null);
```

This code works correct not because apply do not overwrite the bind. It works because non-strict mode.

You may check my tests [here](https://github.com/anzome/nanoevents/blob/tests/test/index.test.js). I added comments there about unexpected behavior. 

Fast googling helped me find clear confirmation only here https://learn.javascript.ru/call-apply (only only russian, within highlighted block). MDN [page](https://github.com/anzome/nanoevents/blob/tests/test/index.test.js) about strict mode contains no precise confirmation of it.

### What does it mean?

It means that without strict mode it is impossible to bind the context while using the i.apply(null, args) or i.apply(this, args). The new example on the readme page is just does not work. And revert of my PR won't fix this problem :(

Enabled strict mode will increase the size of the package up to 113 B. I'm still think about other ways of reducing the size but anyway this is a hard blow.

And, of course, I also searching about ways of replacing `i.apply(null, args)` with direct call of a listener, but I have no strong believe in it is possible.

**Comment by ai** [comment]
Good reason to already add test for changes. My fail that I didn't force you to will tests.

Sorry, 10% of the size is not important for non-critical change.

Let's start from fixing docs (show example work arrow function).

**Comment by anzome** [comment]
You are right. It was my mistake to put too much beleave in manual experimental results. But I have to highlight that my change didn't create the problem. It just made it kind of easier to notice.

Ok. I'll start from docs. Thanks for the advice from where to start.

**Comment by ai** [comment]
I am closing this issue because of the lack of activity here
