### ISSUE TITLE
what about off method ? 

### ISSUE THREAD

**Issue by jt3k** [ai/nanoevents#25]
it should look easy
```
  off(event) {
    delete this.events[event]
  }
```

**Comment by ai** [comment]
Do you need to unbind all event listeners for some specific event? What is use case for this (to understand how it could be popular)?

**Comment by jt3k** [comment]
for example 
```
componentDidMount() {
  bus.on('global click', () => { ... })
}

componentWillUnmount() {
  bus.off('global click');
}
```

**Comment by jt3k** [comment]
Also, this method can be made universal - for deleting subscriptions to all events, or for deleting to a specific one.
```
  off(event) {
    if (event) {
      delete this.events[event]
    } else {
      this.events = {}
    }
  }
```

**Comment by ai** [comment]
We already have API to unbind specific event listeners `unbind = obj.on`.

What is use case to unbind all event listeners for specific event?
