### ISSUE TITLE
event name is still in events keys after unbind.

### ISSUE THREAD

**Issue by dishuostec** [ai/nanoevents#28]
[Example in README.md](https://github.com/ai/nanoevents#events-list) says:
```javascript
const unbind = emitter.on('tick', () => { })
Object.keys(emitter.events) //=> ["tick"]

unbind()
Object.keys(emitter.events) //=> []
```
But after unbind, `Object.keys(emitter.events)` is still contains `"tick"`.

**Comment by ai** [comment]
Thanks. Fixed 05859e5
