### ISSUE TITLE
What the reason to use .filter() method in emit? .forEach() looks much more suitable

### ISSUE THREAD

**Issue by tkusto** [ai/nanoevents#31]

**Comment by ai** [comment]
Better gzip compression, because we used `filter` in another block

**Comment by tkusto** [comment]
Ok, got it, also filter not produces new array as .map() so it is better for performance and memory

**Comment by TrySound** [comment]
But it does produce new array. Filter does not mutate original one.

**Comment by tkusto** [comment]
> But it does produce new array. Filter does not mutate original one.

You are totally right, sorry, looks like I still think about forEach on that moment

**Comment by ai** [comment]
@TrySound nope, `filter` creates new Array, it is immutable operation.

**Comment by tkusto** [comment]
> @TrySound nope, `filter` creates new Array, it is immutable operation.

@TrySound wrote that filter IS immutable.

**Comment by ai** [comment]
I removed this hack. We got enough size in 4.0 to be ready to remove it.

https://github.com/ai/nanoevents/commit/38a1454713f3765ebfbe47a05a4b5ae78206b7e1

**Comment by TrySound** [comment]
Wow, not es5 anymore?

**Comment by ai** [comment]
@TrySound yeap, ES6, ESM and TS will be in all my open source now.
