### ISSUE TITLE
Consider replacing filter in emit

### ISSUE THREAD

**Issue by ianobermiller** [ai/nanoevents#32]
You could replace the call to Array.prototype.filer in emit with the semantically correct forEach to avoid the array allocation, but that would make the code one character longer. 

If you want the code to be shorter and don’t care about the allocation, you could change it to map.

**Comment by ai** [comment]
We had >10% size improvements in 4.0. I think we can remove this hack for better performance.

38a1454

**Comment by ai** [comment]
Released at 4.0.2
