### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by GrosSacASac** [ai/nanoevents#38]
Happens when on and off over time. Simulation:
```js
const emitter = createNanoEvents();
for (let i = 0; i < 1000; i += 1) {
    const off = emitter.on(String(i), console.log);
    // after some time
    off();
}
// emitter.events
// lots of empty arrays that are never deleted
```

**Comment by ai** [comment]
1. I do not like to increase the size to fix problems without a real use case.
2. Main Nano Events use case is using it inside some API, where you have only a limited set of events. [Logux](https://logux.io/node-api/#basenode-on) is a good example. What is your use case?
3. In use case of this simple tets, you can call `emitter.events = {}` to clean all events. I can suggest a better way if I will know the exact use case.

**Comment by GrosSacASac** [comment]
won't fix then I guess, but you should add at least a warning.

**Comment by ai** [comment]
We can add a note to docs about it. Do you have an idea about the text?
