### ISSUE TITLE
No valid exports main found for "/home/node/app/node_modules/nanoevents"

### ISSUE THREAD

**Issue by J0hnnyDaniel** [ai/nanoevents#43]
I have attempted to remove node_modules & package_lock and run npm i again, however, that doesn't seem to fix it.

**Comment by ai** [comment]
@J0hnnyDaniel you need to provide more details

1. How do you use Nano Events? Is it Node.js (what version?) or webpack (what config?)
2. Show the full error text

**Comment by J0hnnyDaniel** [comment]
Using ts-node version 8.6.2, typescript version 3.8.3
Error: No valid exports main found for '/home/node/app/node_modules/nanoevents'
at resolveExportsTarget (internal/modules/cjs/loader.js:625:9)
at applyExports (internal/modules/cjs/loader.js:502:14)
at resolveExports (internal/modules/cjs/loader.js:551:12)
at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)
at Function.Module._load (internal/modules/cjs/loader.js:855:27)
at Module.require (internal/modules/cjs/loader.js:1033:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/home/node/app/node_modules/fun-bots-typescript-routes/index.js:3:22)
at Module._compile (internal/modules/cjs/loader.js:1144:30)

**Comment by J0hnnyDaniel** [comment]
I am using this package inside my own package. The build is successful, however when attempting to use the package I get the above error.

**Comment by ai** [comment]
@J0hnnyDaniel show how do you import NanoEvents

**Comment by J0hnnyDaniel** [comment]
`import { createNanoEvents } from "nanoevents";`
However, keep in mind that this is being converted when building the ts.
Inside the built index.js it is written as so
`"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const nanoevents_1 = require("nanoevents");`

**Comment by ai** [comment]
Can you give me a repository where I can reproduce the error?

**Comment by J0hnnyDaniel** [comment]
Sadly I cannot. The repository is private at the moment.

**Comment by ai** [comment]
Can you create a new repository with minimum files to reproduce the error?

Just put your configs and `index.js` with the simple import

**Comment by J0hnnyDaniel** [comment]
Sure, on it.

**Comment by J0hnnyDaniel** [comment]
It seems that i'm running into difficulties. However I can, at least, inform of how the package nanoevents was used in this code sample:

```
import { createNanoEvents } from "nanoevents";

  export default class Test {
 
    constructor() {
         this.emitter = new createNanoEvents<Events>();
    } 

  }
//Above code was pre-compiled before the below code imported the required package in TS
let item = new Test(); //only this line is being compiled from TS
```
In the actual situation, only the last line is actually ran with .ts, the class and the import being built as .js before being used. 

I presume one of the possible issues could be that when the .js is being built, the way the import is being done is not compatible. However I did not have such issues with other packages until now.

**Comment by ai** [comment]
Tell me more about your project. Is it TypeScript with webpack or just TypeScript?

**Comment by J0hnnyDaniel** [comment]
TypeScript for Node

**Comment by TrySound** [comment]
And which node (not ts-node) version do you use?

**Comment by J0hnnyDaniel** [comment]
13.10.1

**Comment by ai** [comment]
@J0hnnyDaniel what is your `tsconfig.json` content and what do you call before see this error?

**Comment by J0hnnyDaniel** [comment]
The tsconfig of the package is
```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "declaration": true,
    "outDir": "./lib",
    "strict": true
  },
  "include": ["src"],
  "exclude": ["node_modules", "tests/**"]
}
```
The emit function was called within the "onmessage" event of `w3cwebsocket` 
This is the context
```typescript
export default class SomeClass {
    private client: w3cwebsocket;
    private readonly key: string;
    ...
    public readonly emitter;

    constructor(client: w3cwebsocket, key: string) {
        ...
        this.emitter = new EventEmitter();
        ...

        this.client.onmessage = (message: IMessageEvent) => {
            if (typeof message.data === "string") {
            ...
            this.emitter.emit('set', payload.data, payload.statusCode, payload.statusText);
            ...
            }
        }
     }
    ...
}
```

**Comment by ai** [comment]
@J0hnnyDaniel sorry. I tried your config and everything works.

Can you start the new project and copy your code there small bund one by one until you got to have an error?

**Comment by ai** [comment]
@J0hnnyDaniel Can you try the latest Nano EVents 5.1.3?

We fixed one bug for React Native and it could be helpful for you as well.

**Comment by J0hnnyDaniel** [comment]
Hello, after all I made my own implementation and moved on. 
However I'll reopen the issue if sometime in the future I get the issue again.
Thanks, I appreciate you guys trying to help so promptly.
