### ISSUE TITLE
Multiple identical subscriptions

### ISSUE THREAD

**Issue by StreetStrider** [ai/nanoevents#49]
When single function is used as a subscription multiple times (on single event name), then using disposer would remove all copies at once.
This code: `.filter(i => i !== cb)` eliminates all entries, which is counterintuitive for subscriber's party.
One subscription must be removed at a time.
This is the edge case, but worth mentioning.

**Comment by ai** [comment]
Any idea of a solution?

**Comment by StreetStrider** [comment]
The solution is pretty simple, but inevitably affects the size.
1. store first index by `indexOf`
2. filter by this index, `.filter((_, i) => i !== cbi)`

**Comment by ai** [comment]
`Array#splice` will be faster. Can you send PR. Let’s check how many bytes it will add.

**Comment by StreetStrider** [comment]
I didn't offer splice, because it's mutable. As far as I noticed, you guarantee proper disposing during emit (requires copying). I think array splice may still need slicing before to create copy, but not sure. In this conditions your original using of filter looks way wiser.

We can check by running tests.

**Comment by ai** [comment]
Ouh, yeap.

Do we really need this? We can ask users to create a copy of listener (`cb.bind()`) if you add the same listener multiple times.

It is rare case, as I understand.

**Comment by StreetStrider** [comment]
Yes, this is a rare case, I just want it to be mentioned here. Most of the times, subscription is bound to some context or closure, which means it can't be identical.
