### ISSUE TITLE
Won't be smaller and efficient using a `Set`?

### ISSUE THREAD

**Issue by titoBouzout** [ai/nanoevents#60]
I just wrote an event emitter and googled to see how other people were doing. Found this. Very interesting, I wrote something similar but instead of using arrays I figured I could use a Set instead. I was wondering if the code would be smaller, as that seems to be the objective of this library. 

Like 321 chars vs 292 chars, 218 vs 199 (minified)

```js

export let createNanoEvents = () => ({
  events: {},
  emit(event, ...args) {
    ;(this.events[event] || new Set()).forEach(i => i(...args))
  },
  on(event, cb) {
    ;(this.events[event] = this.events[event] || new Set()).add(cb)
    return () =>
      this.events[event].delete(cb)
  }
})
```

I'm also not sure what's your motivation for the defensive programming on the `emit` method. You are creating the event if it doesn't exist. That looks like code smell and could be confusing. If someone is trying to emit an event for something that doesn't exist, it should just fail?

If you want to keep that behaviour, you may make it smaller by using an array for that case, as its just useless. 

```js
export let createNanoEvents = () => ({
  events: {},
  emit(event, ...args) {
    ;(this.events[event] || []).forEach(i => i(...args))
  },
  on(event, cb) {
    ;(this.events[event] = this.events[event] || new Set()).add(cb)
    return () =>
      this.events[event].delete(cb)
  }
})
```

I would prefer instead 

```js
export let createNanoEvents = () => ({
  events: {},
  emit(event, ...args) {
    this.events[event].forEach(i => i(...args))
  },
  on(event, cb) {
    ;(this.events[event] = this.events[event] || new Set()).add(cb)
    return () =>
      this.events[event].delete(cb)
  }
})
```

I wanted to send a pull request, but I am too lazy to deal with all that typescript :P 

Good luck!

**Comment by ai** [comment]
Nope, adding `Set` with keeping current API will increase the size :(

**Comment by titoBouzout** [comment]
Ah yeah, if you still want to check if the event exists when you are trying to turn it off then maybe. Is it worth that check? What about 

```js
return () =>
     this.events[event] && this.events[event].delete(cb)
```

Can you post the minified Set? I found it weird it's bigger

**Comment by ai** [comment]
`.?` is not supported by Node.js 12

**Comment by titoBouzout** [comment]
Got intrigued, tried some variations for a while, and got one that came smaller gzipped without doing anything crazy.

I used https://github.com/prantlf/minified-size for the following results

| version     | B         | minified    | gzipped   | brotlied   |
| ----------- | --------- | ----------- | --------- | ---------- |
| Published   | 306       | 218         | 151       | 132        |
| Variation| 334 (+28) | 240 (+22)   | 149 (-2)  | 123 (-9)   |


Variation:
```js
export let createNanoEvents = () => ({
	events: {},
	emit(event, ...args) {
		;(this.events[event] = this.events[event] || new Set()).forEach(i => i(...args))
	},
	on(event, cb) {
		;(this.events[event] = this.events[event] || new Set()).add(cb)
		return () => (this.events[event] = this.events[event] || new Set()).delete(cb)
	},
})
```

**Comment by ai** [comment]
I added [simple benchmark](https://github.com/ai/nanoevents/blob/main/test/benchmark.js).

And found that `Set` is 2x times slower:

```
# array
emit  64,439,356 ops/sec
on    22,214,388 ops/sec
```

```
# set
emit  32,251,645 ops/sec
on    11,554,681 ops/sec
```
