### ISSUE TITLE
The info in About section is outdated

### ISSUE THREAD

**Issue by kubk** [ai/nanoevents#61]
In the About section it says 72 kb, but it is 99 kb in README

<img width="1369" alt="Screen Shot 2022-04-19 at 17 13 51" src="https://user-images.githubusercontent.com/22447849/164024184-d5888a33-8ff0-4568-a4ec-cfaecac7304e.png">

Since the About section is out of version control, I can't create a PR to fix it. "it ain't much but it's honest work"

**Comment by ai** [comment]
Fixed. Thanks. Seems like I forgot.
