### ISSUE TITLE
Can't Compile with Declarations

### ISSUE THREAD

**Issue by johnnyshankman** [ai/nanoevents#64]
See: https://github.com/ai/nanoevents/issues/40

I'm having the same issue but on `7.0.1`

```
 ERROR  Failed to compile with 1 error                                                                       2:21:48 PM

 error  in /node_modules/nanoevents/index.js

Module parse failed: Unexpected token (10:23)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   },
|   on(event, cb) {
>     this.events[event]?.push(cb) || (this.events[event] = [cb])
|     return () => {
|       this.events[event] = this.events[event]?.filter(i => cb !== i)
```

Rolling back to 6.0.0 solves it for me. Changing my `.tsconfig.js` to have `"declaration": false` also fixes it but obviously that's not a solve, I need types. I do not have this issue with any other node module in my pkg.

**Comment by ai** [comment]
What Node.js version and `tsconfig.js` do you have?

**Comment by anderson-comvex** [comment]
We are having the same issue with node `14.18.1`, nanoscripts version `7.0.1`

**Comment by ai** [comment]
@anderson-comvex show your `tsconfig.js`
